---
title: Welcome to Homework 2
date: last-modified
author: Antony Fuentes
format:
    gfm:
        mermaid-format: png
---

This is my solution to homework 2. I'm using Quarto render this document from a QMD file to a regular
MD file for display on GITHUB.

## Scenario

Imagine you're designing a Library Management System for a small local library. The system needs to track information about books and library members. Each book has a unique ISBN (International Standard Book Number), a title, and a publication year. Each library member is identified by a unique member ID, and the system needs to store their name and contact information. Library members can check out books, but they don’t have to.

## Design Task 1

Identify and document the entities, attributes, and relationships using Chen notation.
```{dot}
graph ER {
    layout=neato;
    scale=1.1;
    node [shape=box]; Book; Member;
    node [shape=ellipse]; ISBN, Title, Publication_Year, Member_ID, Name, Contact_Info;
    node [shape=diamond,style=filled,color=lightgrey]; has
    
    Book -- has [label="1",len=1.00]
    has -- Member [label="n",len=1.00]
    
    Book -- ISBN
    Book -- Title
    Book -- Publication_Year
    Member -- Member_ID
    Member -- Name
    Member -- Contact_Info

}
```

## Design Task 2

Identify and document the entities, attributes, and relationships using Crow’s Foot notation.
```{mermaid}

    ```
